#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: hrcnthu/lerobot-koch-actpp:gpu

  volumes:
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /dev/shm:/dev/shm
  
  environment:
    - DISPLAY=${DISPLAY}
  
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev


############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    

##############################
###   Container Services   ###
##############################
services:
  void:
    <<: [*common]
    container_name: koch-actpp-void

    volumes:
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
      
    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/bin/bash"]


  armv:
    <<: [*common, *gpu]
    container_name: koch-actpp-armv

    volumes:
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
    
    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/root/entrypoint/armv.sh"]

  
  armv-rec:
    <<: [*common, *gpu]
    container_name: koch-actpp-armv-rec

    volumes:
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
    
    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/root/entrypoint/armv-rec.sh"]


  
  actpp-train:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-train
  

  actpp-deploy:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-deploy