#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: hrcnthu/lerobot-koch-actpp:gpu

  volumes:
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /dev/shm:/dev/shm
  
  environment:
    - DISPLAY=${DISPLAY}
  
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev


############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    

##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common, *gpu]
    container_name: koch-actpp-raw

    volumes:
      ## NOTE: mount .git to setup the git credentials
      #  you can comment out this line, 
      #  if you don't need to upload dataset to huggingface.
      - ../../.git/:/root/.git
      
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
      
    entrypoint: ["/root/entrypoint/symlinks.sh", "/root/entrypoint/token.sh"]
    command: ["/bin/bash"]


  arm-sync:
    <<: [*common, *gpu]
    container_name: koch-actpp-arm-sync

    volumes:
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
    
    entrypoint: ["/root/entrypoint/symlinks.sh", "/root/entrypoint/token.sh"]
    command: ["/root/entrypoint/arm-sync.sh"]

  
  armv-rec:
    <<: [*common, *gpu]
    container_name: koch-actpp-armv-rec

    volumes:
      - ../entrypoint:/root/entrypoint
      - ../../lerobot:/root/lerobot
    
    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/root/entrypoint/armv-rec.sh"]


  
  actpp-train:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-train
  

  actpp-deploy:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-deploy